---
abstract: 'Stream TAP from MyTAP test scripts'
author:
  - 'David E. Wheeler <dwheeler@cpan.org>'
build_requires:
  Module::Build: 0.30
  Test::More: 0.88
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TAP-Parser-SourceHandler-MyTAP
provides:
  TAP::Parser::SourceHandler::MyTAP:
    file: lib/TAP/Parser/SourceHandler/MyTAP.pm
    version: 3.24
recommends:
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
requires:
  TAP::Parser::SourceHandler: 0
  perl: 5.006
resources:
  bugtracker: http://github.com/theory/tap-parser-sourcehandler-mytap/issues/
  homepage: http://search.cpan.org/dist/Tap-Parser-Sourcehandler-MyTAP/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/tap-parser-sourcehandler-mytap/tree/
version: 3.24
